chore:  add comments to clarify intention of lock file copy step

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -52,9 +52,13 @@ runs:
 
     - name: Copy workspaces lock file to subfolders
       if: ${{inputs.yarn-workspaces == 'true'}}
+      # The intention in the below command is to copy the yarn.lock from the root workspace to the other workspaces 
+      # as a workaround since Mend does not support yarn workspaces as of the writing of this step.
+      # The file check is to ensure we skip the root workspace without explicitly having to pass the name of the workspace.
+      # Forcing the exit 0 is meant to not fail the step when the root workspace is encountered.
       run: |
           export ROOT_WORKSPACE=$(pwd)
-          yarn workspaces foreach exec '[ ! -f "./yarn.lock" ] && cp $ROOT_WORKSPACE/yarn.lock . || exit 0'
+          yarn workspaces foreach exec '[ ! -r "./yarn.lock" ] && cp $ROOT_WORKSPACE/yarn.lock . || exit 0'
 
     - name: Scan
       shell: bash
@@ -64,13 +68,13 @@ runs:
         WS_CHECKPOLICIES: ${{inputs.check-policies}}
         WS_UPDATEINVENTORY: ${{inputs.update-inventory}}
       run: |
-          echo Downloading Mend Unified Agent
+          echo 'Downloading Mend Unified Agent'
           curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
           if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
-            echo "Integrity Check Failed"
+            echo 'Integrity Check Failed'
             exit 1
           else
-            echo "Integrity Check Passed"
-            echo Starting Mend Scan
+            echo 'Integrity Check Passed'
+            echo 'Starting Mend Scan'
             java -jar wss-unified-agent.jar -c ${{inputs.config-file-path}} -d ${{inputs.locations-to-scan}} -logLevel ${{inputs.log-level}}
           fi
